### ISSUE TITLE
.re hard to use reliably

### ISSUE THREAD

**Issue by stephane-chazelas** [raforg/rawhide#2]
```
rh -e '"\.txt$".re'
```

Matches on a file called `foo.txt` but also on one called `$'foo.txt\nbar.exe'` as the  `PCRE2_MULTILINE` (`m`) flag is  enabled by default.

```
rh -e '"(?-m)\.txt$".re'
```

Helps but that still matches on a file called `$'foo.txt\n'` as the `PCRE2_DOLLAR_ENDONLY` flag is not enabled.

The usual work around (also needed in commands such as perl-based `rename` implementations) is to use `\z` in  place of `$` which always matches at the end of the subject even if PCRE2_MULTILINE is enabled and/or PCRE2_DOLLAR_ENDONLY is not enabled:

```
rh -e '"\.txt\z".re'
```

But then I find that it still matches on a file called `$'foo.txt\x80bar.exe'`. Possibly linked to the PCRE2_MATCH_INVALID_UTF flag.

That sounds like it could be a bug in PCRE2 but I can't reproduce it with `pcre2grep -U`.

To match on files whose name ends in `.txt`, I find that I need:

```
rh -e '"\.txt\z$".re'
```

Or:

```
RAWHIDE_PCRE2_NOT_UTF8_DEFAULT=1 rh -e '"\.txt\z".re'
```

It seems to me pcre2 should be invoked with different default options when it's meant to match on lines (like in `.rebody`) where using PCRE2_MULTILINE only would make sense and when meant to match on whole strings (like in `.re`) where PCRE2_DOTALL|PCRE2_DOLLAR_ENDONLY would be more useful (and with PCRE2_EXTENDED|PCRE2_EXTENDED_MORE|PCRE2_NO_AUTO_CAPTURE|PCRE2_UTF|PCRE2_MATCH_INVALID_UTF in common as required).

---

Note that:

```
rh -e '"*.txt"'
```

Would fail to match on `$'foo\x80bar.txt'`  in a UTF-8 locale with the `fnmatch()` of older versions of glibc which you'd work around by using `LC_ALL=C rh -e '"*.txt"'` (same as for `find -name` (or `find -regex` where supported)). It matches in newer versions but I believe it's because/thanks of [that bug](https://sourceware.org/bugzilla/show_bug.cgi?id=31075).

----

### Context

Here tested with the current git HEAD of rawhide (a1c44e2fab883489bbb9fbebfc7dc87dfbfc14cf) on Debian GNU/Linux amd64 with

```
libc6 2.37-12
libpcre2-8-0 10.42-4
```

**Comment by stephane-chazelas** [comment]
[...]
> ```
> rh -e '"\.txt\z".re'
> ```
> 
> But then I find that it still matches on a file called `$'foo.txt\x80bar.exe'`. Possibly linked to the PCRE2_MATCH_INVALID_UTF flag.
> 
> That sounds like it could be a bug in PCRE2 but I can't reproduce it with `pcre2grep -U`.
[...]

Actually I can reproduce with:

```
$ echo $'foo.txt\x80bar.exe' | pcre2grep --no-jit -U '\.txt\z'
foo.txt�bar.exe
```

Or with the `pcre2grep` that results from compiling pcre2 with the default `configure` options (without `--enable-jit` which Debian adds). So that part is a PCRE bug after all. I'll raise it there.

**Comment by stephane-chazelas** [comment]
In any case even with that PCRE2 bug fixed, unless `PCRE2_MULTILINE` is removed and `PCRE2_DOTALL` added for `.re`, there are a number of examples in the `rh.1` man page where `^` should be replaced with `\A` and `$` with `\z` (and possibly `(?-m)` added).

For instance:

>            $ rh '"
>              ^         # Anchor the match to the start of the base name
>              \w+       # Starts with at least one word character
>              \d{2,3}   # Followed by two or three digits
>              \.        # Followed by a literal dot
>              .*        # Followed by anything (or nothing)
>              [ a-c z ] # Ends with a, b, c, or z
>              $         # Anchor the match to the end of the base name
>            ".re'

Should be:

```
           $ rh '"
             (?-m)     # Disable multi-line as we want to match the
                       # filename as a whole
             ^         # Anchor the match to the start of the base name
             \w+       # Starts with at least one word character
             \d{2,3}   # Followed by two or three digits
             \.        # Followed by a literal dot
             .*        # Followed by anything (or nothing)
             [ a-c z ] # Ends with a, b, c, or z
             \z        # Anchor the match to the end of the base name
           ".re'
```

Or:

```
           $ rh '"
             \A        # Anchor the match to the start of the base name
                       # Do not use ^ which would match at the start of
                       # any line in the file name
             \w+       # Starts with at least one word character
             \d{2,3}   # Followed by two or three digits
             \.        # Followed by a literal dot
             .*        # Followed by anything (or nothing)
             [ a-c z ] # Ends with a, b, c, or z
             \z        # Anchor the match to the end of the base name
           ".re'
```

**Comment by raforg** [comment]
Thanks! The general consensus in the perl community is that all regular expressions should have the `/smx` flags. That why `PCRE2_MULTILINE` is always present. But of course you're right. The security implications are more important than a general purpose convention. The convention assumes lines that end with a newline and that newlines should be accepted easily and mostly ignored. But they weren't thinking about malicious file names.

I don't have a huge problem with needing `\z` rather than `$`. That makes sense for perl. But I agree that it would be better if users can use `$` like I already have it in the examples you mentioned.

And I really don't want users to need `\z$`. Nobody will do that.

It's wierd. I can't reproduce the need for `\z$` here (debian12, libpcre2-8-0 10.42-1). I'm not seeing a difference between `'"\.txt\z".re'` and `'"\.txt\z$".re'` even in a UTF-8 locale. But I'm sure you're right.

How's the latest commit? It looks good to me.

**Comment by stephane-chazelas** [comment]
> Thanks! The general consensus in the perl community is that all regular expressions should have the `/smx` flags.

Strange, I've been using perl for over 25 years but have never come across recommendations to use /smx by default. But then again I don't hang out on perl fora or mailing lists.

To me `m` is used when you want to match lines in multiline strings, but then you generally don't want `s` as that means you'd need `[^\n]` instead of `.` (in any case, you need to watch out for things like `\s`, `\W`, `[^x]` also matching newline). `pcregrep -M` does enable `m` and not `s` (as well as pulling more lines in the subject as needed).

And you use `s` to match on strings as a whole, like in `rename` where you need `rename 's{^.*?\[(\d+)\].*\.txt\z}{$1.txt}s' ./*`.

(and `x` when you want to improve the  legibility of long and complex regexps).

In any case, I agree PCRE2_DOLLAR_ENDONLY should be always on (though it won't make a difference with PCRE2_MULTILINE as `$` always matches at the end of the line there).

The behaviour without PCRE2_DOLLAR_ENDONLY doesn't make much sense to me. Either you want to match on lines and you use the `m` flag or you don't and `$` should match at the end of the subject. I understand it comes from perl's `<>`, `<X>` operators which contrary to perl/sed leave the line delimiters in (which is a good thing as it allows coping better with non-delimited lines), but even there, using the `m` flag to deal with those lines would probably make more sense.

[...]
> It's wierd. I can't reproduce the need for `\z$` here (debian12, libpcre2-8-0 10.42-1). I'm not seeing a difference between `'"\.txt\z".re'` and `'"\.txt\z$".re'` even in a UTF-8 locale. But I'm sure you're right.

It seems whether JIT is enabled has an influence on the matter. Looking at the PCRE bug, it looks like they haven't gone to the bottom of it yet.

> How's the latest commit? I've implemented your recommendations, and It looks good to me.

Much better. I'll send a few more comments via email.

But for this matter, would you consider removing DOTALL for multiline matches to align with the `pcregrep` behaviour?

**Comment by macportsraf** [comment]
> Strange, I've been using perl for over 25 years but have never come across recommendations to use /smx by default.

It's from Damian Conway's "Perl Best Practices" book. And perlcritic's default policies are mostly based on that book.

> would you consider removing DOTALL for multiline matches to align with the pcregrep behaviour?

Sure. It's done. If anyone wants it back, there's an environment variable for it (same with /m).

**Comment by raforg** [comment]
Actually, I'm not too keen on removing DOTALL from `.body`. I like the fact that `.body` isn't line-oriented and instead matches the entire content (easily). I've already had uses where I'm looking for files with something in one line, and something further down in the file. That's something that (I think) *grep* and *ripgrep* and presumably *pcregrep* can't do, because they are all mostly line-oriented. And I think it's better default behaviour. I know it's silly that it reads in the entire file, but since it does, it makes sense to make the most use of that fact. It's probably the main reason it is reading in the whole file (to make it simple to match on the whole file).

Would it be acceptable if I inverted the last change so that `DOTALL` is always there by default, but there's an environment variable to remove /s from the default (for multi-line subject text)?

**Comment by stephane-chazelas** [comment]
You can always use `(?s)` or `(?s:...)` to have parts of the regexp match multiple lines like you'd do in `pcregrep -M`:

```
$ seq -f foo%g 10 | pcregrep -M '(?x) ^f.*4$ (?s:.*?) ^f.*7$'
foo4
foo5
foo6
foo7
```

Above matching from a `f.*4` line to a `f.*7` line.

In the end, it has to be down to what is most likely to be useful and less surprising for users.

For me, if makes sense that if `^` and `$` are to match at the start and end of each line, that means you want to match lines individually so `.*` should not match across lines, and I regard `s` and `m` (single vs multi) as being somewhat antinomic.

But then again, as I said, I was not familiar with that recommendation of using them together as a default rule so I may not be a good reference, and I've only been aware of `rh` for a week and have not used it much yet. In the end, it's your decision. Which ever way is workable as the flag can be turned on or off with `(?s)`, `(?-s)`.

One could also argue that not many people are familiar with perl regexps and few may be aware of those `(?s)`, `(?m)`, `(?-s)`... And doing `[^\n]*` when `s` is on would be simpler than using `(.|\n)*` when it's off.

How about ACLs? For instance `^user:.+:.w` could be problematic if that `.+` spanned several lines (but then again `^user:[^:]+:.w` would span several lines with or without the `s` flag and you'd need `[^:\n]+`).

**Comment by macportsraf** [comment]
OK. The ACL argument convinced me. Security by default beats everything else (even if `reacl` searches will be much less common than `rebody` searches). I've also changed the `reacl` examples that used `[^:]+` to use `[^:\n]+` instead. Thanks for that. The latest commit adds documentation about this change everywhere it's needed.

> But then again, as I said, I was not familiar with that recommendation of using them together as a default rule so I may not be a good reference

Maybe you are. I don't follow Damian's best practice either. I don't know what proportion of perl programmers do. I assume it's a lot, but I don't know. More importantly, I don't think command line tools should require too much knowledge about perl. That's why I prefer my `mved` program to Larry Wall's `rename` program. Anyone can use it, not just perl programmers. In the case of `rawhide`, knowledge of perl regex is hugely beneficial, but users can always use the glob syntax instead if they don't know perl regex. But if they are willing to use regex, I'm happy to insist on perl regex. It is the best, especially when dealing with unicode.

> In the end, it has to be down to what is most likely to be useful and less surprising for users.

Yes. Assuming `/s` for single lines and `/m` for multiple lines does make sense. It's what perl programmers have done for decades, before the best practices book, and so it's a better default. I've made it so that anyone who prefers the perl best practices can have that with environment variables, and I've clearly documented how to override the defaults for individual matches. I'm happy with it.

> One could also argue that not many people are familiar with perl regexps and few may be aware of those (?s), (?m), (?-s)...

I'd never used them. When using perl, one tends to use `/s` and `/m` instead. So thanks for that. The new documentation explains when they can be used.

> And doing [^\n]* when s is on would be simpler than using (.|\n)* when it's off.

True, but they are both hideous. I'd prefer using `(?s)` and `(?-s)` so that I can still use `.*`.

Many thanks. Even though this is technically not backwards compatible (which I hate), I'm sure it's an improvement. And there won't be enough users yet for it to be a problem.
